common: &defaults
  adapter:  postgresql
  encoding: unicode
  database: blog_<%= Rails.env %>
  pool:     5
  username: grogblog
  password:

development:
  <<: *defaults

test:
  <<: *defaults

cucumber:
  <<: *defaults

production:
  <<: *defaults
  database: blog

